########################################
#
#  GLOBAL VARIABLES
#
########################################

@baseUrl=http://localhost:{{$dotenv APP_PORT_EXTERNAL}}/api
@accept=application/json
@contentType=application/json

########################################
#
#  AUTHORIZATION
#
########################################

### Login / Access Token Generation
# @name authLogin

POST {{baseUrl}}/auth/login
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "email": "default@app.com",
    "password": "defaultpassword"
}

### Access Token Definition

@accessToken={{authLogin.response.body.data.access_token}}

# To delete tokens, you can use this code on Laravel Tinker: \App\Domain\User\Models\User::find(1)->tokens()->delete();

### Get Authenticated User Data
# @name authMe

GET {{baseUrl}}/auth/me
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  DOCUMENT TYPES
#
########################################

### Get List Of Document Types

GET {{baseUrl}}/document-types
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Show Specific Document Type

GET {{baseUrl}}/document-types/2
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  USER TYPES
#
########################################

### Get List Of User Types

GET {{baseUrl}}/user-types
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Show Specific User Type

GET {{baseUrl}}/user-types/1
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  USERS
#
########################################

### Create New User (of the user type COMMON)

POST {{baseUrl}}/users
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "user_type_id": 1,
    "name": "Peter Parker",
    "document_type_id": 2,
    "document_number": "06633022000",
    "email": "peter.parker@marvel.com",
    "password": "UKyEuc2Bh0ZDKjQ",
    "starter_balance": 450
}

### Create New User (of the user type SHOPKEEPER)

POST {{baseUrl}}/users
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "user_type_id": 2,
    "name": "Wayne Tech",
    "document_type_id": 1,
    "document_number": "09625891000146",
    "email": "wayne.tech@dccomics.com",
    "password": "UKyEuc2Bh0ZDKjQ",
    "starter_balance": 450.20
}

### Update User (of the user type COMMON)

PATCH {{baseUrl}}/users/1
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "John Alexander Doe",
    "document_number": "70349142068",
    "email": "john.alex.doe@test.com"
}

### Update User (of the user type SHOPKEEPER)

PATCH {{baseUrl}}/users/3
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

{
    "name": "Pokemon Adventurer Company",
    "document_number": "10100518000150"
}

### Delete User

DELETE {{baseUrl}}/users/5
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Get List Of Users

GET {{baseUrl}}/users
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Show Specific User

GET {{baseUrl}}/users/1
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  EXTERNAL AUTHORIZATION
#
########################################

### Authorize (with third party service)

GET https://util.devi.tools/api/v2/authorize
