########################################
#
#  GLOBAL VARIABLES
#
########################################

@baseUrl=http://localhost:{{$dotenv APP_PORT_EXTERNAL}}/api
@accept=application/json
@contentType=application/json

########################################
#
#  AUTHORIZATION
#
########################################

### Login / Access Token Generation
# @name authLogin

POST {{baseUrl}}/auth/login
Accept: {{accept}}
Content-Type: {{contentType}}

{
    "email": "default@app.com",
    "password": "defaultpassword"
}

### Access Token Definition

@accessToken={{authLogin.response.body.data.access_token}}

# To delete tokens, you can use this code on Laravel Tinker: \App\Domain\User\Models\User::find(1)->tokens()->delete();

### Get Authenticated User Data
# @name authMe

GET {{baseUrl}}/auth/me
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  DOCUMENT TYPES
#
########################################

### Get List Of Document Types

GET {{baseUrl}}/document-types
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Show Specific Document Type

GET {{baseUrl}}/document-types/2
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

########################################
#
#  USER TYPES
#
########################################

### Get List Of User Types

GET {{baseUrl}}/user-types
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}

### Show Specific User Type

GET {{baseUrl}}/user-types/1
Accept: {{accept}}
Content-Type: {{contentType}}
Authorization: Bearer {{accessToken}}
